# Generated by Django 3.2.23 on 2024-01-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20240118_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcharginglocation',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
