# Generated by Django 3.2.23 on 2024-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_auto_20240118_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcharginglocation',
            name='facebook',
            field=models.CharField(max_length=250),
        ),
    ]
