# Generated by Django 3.2.23 on 2024-01-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_alter_evcharginglocation_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('telnumber', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='EVChargingLocation',
        ),
    ]
